version: '3.8'

services:
  models-base:
    build:
      context: .
      dockerfile: ./models/shared/Dockerfile
    image: models-base

  webapi:
    build:
      context: .
      dockerfile: Presentation/WebApp/Dockerfile
      target: runtime
    ports:
      - "8511:8080"
    env_file:
      - .env
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      ConnectionStrings__Default: Host=${PostgreSqlConfiguration__Host};Port=${PostgreSqlConfiguration__Port};Database=${PostgreSqlConfiguration__DatabaseName};Username=${PostgreSqlConfiguration__Username};Password=${PostgreSqlConfiguration__Password}
      Jwt__SecretKey: ${TokenInfoConfiguration__Secret}
    depends_on:
      - db
      - emotion-server
      - recommendation-server
    working_dir: /app

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PostgreSqlConfiguration__DatabaseName}
      POSTGRES_USER: ${PostgreSqlConfiguration__Username}
      POSTGRES_PASSWORD: ${PostgreSqlConfiguration__Password}
    volumes:
      - pgdata:/var/lib/postgresql/data

  emotion-server:
    build:
      context: ./models/emotion-server
      args:
        HF_TOKEN: ${HF_TOKEN}
    ports:
      - "5000:5000"
    volumes:
      - transformers_cache:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1m
      timeout: 10s
      retries: 5
    environment:
      - HF_TOKEN=${HF_TOKEN}
    depends_on:
      - models-base

  recommendation-server:
    build:
      context: ./models/recommendation-server
      args:
        HF_TOKEN: ${HF_TOKEN}
    ports:
      - "5001:5001"
    volumes:
      - transformers_cache:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 1m
      timeout: 10s
      retries: 5
    depends_on:
      - models-base

volumes:
  pgdata:
  transformers_cache: