version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Presentation/WebApp/Dockerfile
      target: build
    command: [ ]
    entrypoint:
      - "dotnet"
      - "/app/bin/VibeNote/net8.0/WebApp.dll"
    ports:
      - "8511:8080"
    env_file:
      - .env
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      ConnectionStrings__Default: Host=${PostgreSqlConfiguration__Host};Port=${PostgreSqlConfiguration__Port};Database=${PostgreSqlConfiguration__DatabaseName};Username=${PostgreSqlConfiguration__Username};Password=${PostgreSqlConfiguration__Password}
      Jwt__SecretKey: ${TokenInfoConfiguration__Secret}
    depends_on:
      - db
    volumes:
      - ${USERPROFILE}/.nuget/packages:/root/.nuget/packages:ro
      - ./Presentation/WebApp:/app:rw
      - .:/src:rw
    working_dir: /app

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PostgreSqlConfiguration__DatabaseName}
      POSTGRES_USER: ${PostgreSqlConfiguration__Username}
      POSTGRES_PASSWORD: ${PostgreSqlConfiguration__Password}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
