version: '3.8'

services:
  webapi:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=${PostgreSqlConfiguration.Host};Port=${PostgreSqlConfiguration.Port};Database=${PostgreSqlConfiguration.DatabaseName};Username=${PostgreSqlConfiguration.Username};Password=${PostgreSqlConfiguration.Password}
      - Jwt__SecretKey=${TokenInfoConfiguration.Secret}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PostgreSqlConfiguration.DatabaseName}
      POSTGRES_USER: ${PostgreSqlConfiguration.Username}
      POSTGRES_PASSWORD: ${PostgreSqlConfiguration.Password}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: