server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}

    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log

    relabel_configs:
      - source_labels: [__path__]
        regex: /var/lib/docker/containers/([a-z0-9]+)/*.log
        target_label: container_id

      - source_labels: [container_id]
        regex: (.+)
        target_label: __meta_docker_container_id

      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: container_name